(cl:in-package dynamixel_workbench_msgs-msg)
(cl:export '(MODEL_NUMBER-VAL
          MODEL_NUMBER
          FIRMWARE_VERSION-VAL
          FIRMWARE_VERSION
          ID-VAL
          ID
          BAUD_RATE-VAL
          BAUD_RATE
          RETURN_DELAY_TIME-VAL
          RETURN_DELAY_TIME
          CW_ANGLE_LIMIT-VAL
          CW_ANGLE_LIMIT
          CCW_ANGLE_LIMIT-VAL
          CCW_ANGLE_LIMIT
          TEMPERATURE_LIMIT-VAL
          TEMPERATURE_LIMIT
          MIN_VOLTAGE_LIMIT-VAL
          MIN_VOLTAGE_LIMIT
          MAX_VOLTAGE_LIMIT-VAL
          MAX_VOLTAGE_LIMIT
          MAX_TORQUE-VAL
          MAX_TORQUE
          STATUS_RETURN_LEVEL-VAL
          STATUS_RETURN_LEVEL
          ALARM_LED-VAL
          ALARM_LED
          SHUTDOWN-VAL
          SHUTDOWN
          MULTI_TURN_OFFSET-VAL
          MULTI_TURN_OFFSET
          RESOLUTION_DIVIDER-VAL
          RESOLUTION_DIVIDER
          TORQUE_ENABLE-VAL
          TORQUE_ENABLE
          LED-VAL
          LED
          D_GAIN-VAL
          D_GAIN
          I_GAIN-VAL
          I_GAIN
          P_GAIN-VAL
          P_GAIN
          GOAL_POSITION-VAL
          GOAL_POSITION
          MOVING_SPEED-VAL
          MOVING_SPEED
          TORQUE_LIMIT-VAL
          TORQUE_LIMIT
          PRESENT_POSITION-VAL
          PRESENT_POSITION
          PRESENT_SPEED-VAL
          PRESENT_SPEED
          PRESENT_LOAD-VAL
          PRESENT_LOAD
          PRESENT_VOLTAGE-VAL
          PRESENT_VOLTAGE
          PRESENT_TEMPERATURE-VAL
          PRESENT_TEMPERATURE
          REGISTERED-VAL
          REGISTERED
          MOVING-VAL
          MOVING
          LOCK-VAL
          LOCK
          PUNCH-VAL
          PUNCH
          GOAL_ACCELERATION-VAL
          GOAL_ACCELERATION
))