function J_aug = function_J_aug(rot_RF3_1,rot_RF3_2,rot_RF3_3,LTz,LTx,LTy,LSy,LFy,LFx)
%FUNCTION_J_AUG
%    J_AUG = FUNCTION_J_AUG(ROT_RF3_1,ROT_RF3_2,ROT_RF3_3,LTZ,LTX,LTY,LSY,LFY,LFX)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    01-May-2020 23:53:21

t2 = LFy+LSy+LTy;
t3 = cos(LFx);
t4 = sin(LFx);
t5 = cos(t2);
t6 = rot_RF3_3.*t3;
t7 = rot_RF3_2.*t4;
t8 = t6+t7;
t9 = sin(t2);
t11 = cos(LTz);
t12 = cos(LTx);
t13 = rot_RF3_2.*t3;
t14 = rot_RF3_3.*t4;
t15 = t13-t14;
t16 = t12.*t15;
t17 = sin(LTx);
t18 = t5.*t8;
t19 = rot_RF3_1.*t9;
t20 = t18-t19;
t21 = t17.*t20;
t22 = t16-t21;
t23 = sin(LTz);
t24 = rot_RF3_1.*t5;
t25 = t8.*t9;
t26 = t24+t25;
t27 = t11.*t26;
t28 = t22.*t23;
t10 = t27+t28;
t29 = t10.^2;
t30 = -t29+1.0;
t31 = 1.0./sqrt(t30);
t32 = t11.*t20;
t33 = t17.*t23.*t26;
t34 = t32+t33;
J_aug = [0.0,0.0,0.0,0.0,0.0,0.0,-t31.*(t11.*t22-t23.*t26),t23.*t31.*(t12.*t20+t15.*t17),-t31.*t34,-t31.*t34,-t31.*t34,t31.*(t23.*(t8.*t12+t5.*t15.*t17)-t9.*t11.*t15),0.0,0.0,0.0,0.0,0.0,0.0,0.0];
