ADDR_RX_TORQUE_ENABLE = 24;
LEN_RX_TORQUE_ENABLE = 1;
enable = zeros(1,19);

Dynamixel.SendVector(enable, ADDR_RX_TORQUE_ENABLE, LEN_RX_TORQUE_ENABLE);

clear ADDR_RX_TORQUE_ENABLE LEN_RX_TORQUE_ENABLE enable;