function J_aug = function_J_aug(rot_RF3_1,rot_RF3_2,rot_RF3_3,RTz,RTx,RTy,RSy,RFy,RFx)
%FUNCTION_J_AUG
%    J_AUG = FUNCTION_J_AUG(ROT_RF3_1,ROT_RF3_2,ROT_RF3_3,RTZ,RTX,RTY,RSY,RFY,RFX)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    01-May-2020 23:22:17

t2 = RFy+RSy+RTy;
t3 = cos(RFx);
t4 = sin(RFx);
t5 = cos(t2);
t6 = rot_RF3_3.*t3;
t7 = rot_RF3_2.*t4;
t8 = t6+t7;
t9 = sin(t2);
t11 = sin(RTz);
t12 = rot_RF3_1.*t5;
t13 = t8.*t9;
t14 = t12+t13;
t15 = cos(RTz);
t16 = cos(RTx);
t17 = rot_RF3_2.*t3;
t18 = rot_RF3_3.*t4;
t19 = t17-t18;
t20 = t16.*t19;
t21 = sin(RTx);
t22 = t5.*t8;
t23 = rot_RF3_1.*t9;
t24 = t22-t23;
t25 = t21.*t24;
t26 = t20-t25;
t27 = t14.*t15;
t28 = t11.*t26;
t10 = t27+t28;
t29 = t10.^2;
t30 = -t29+1.0;
t31 = 1.0./sqrt(t30);
t32 = t15.*t24;
t33 = t11.*t14.*t21;
t34 = t32+t33;
J_aug = [t31.*(t11.*t14-t15.*t26),t11.*t31.*(t16.*t24+t19.*t21),-t31.*t34,-t31.*t34,-t31.*t34,t31.*(t11.*(t8.*t16+t5.*t19.*t21)-t9.*t15.*t19),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0];
