(cl:defpackage dynamixel_workbench_msgs-srv
  (:use )
  (:export
   "DYNAMIXELCOMMAND"
   "<DYNAMIXELCOMMAND-REQUEST>"
   "DYNAMIXELCOMMAND-REQUEST"
   "<DYNAMIXELCOMMAND-RESPONSE>"
   "DYNAMIXELCOMMAND-RESPONSE"
   "GETDYNAMIXELINFO"
   "<GETDYNAMIXELINFO-REQUEST>"
   "GETDYNAMIXELINFO-REQUEST"
   "<GETDYNAMIXELINFO-RESPONSE>"
   "GETDYNAMIXELINFO-RESPONSE"
  ))

